import { NextResponse } from "next/server";
import catalog from "@/data/journal-catalog.json";
import { requireFullAccess } from "@/lib/access";

// Static catalog generated by scripts/build-journal-catalog.mjs
// (npm run journal-catalog:build). Served from here rather than imported
// client-side, to keep it out of the page's initial JS bundle — same pattern
// as /api/market/items and /api/crafting/recipes.
export async function GET() {
  const access = await requireFullAccess();
  if (!access.ok) return access.response;

  return NextResponse.json({ items: catalog });
}
