import { NextResponse } from "next/server";
import catalog from "@/data/farming-catalog.json";
import { requireFullAccess } from "@/lib/access";

// Static catalog generated by scripts/build-farming-catalog.mjs
// (npm run farming-catalog:build). Served from here rather than imported
// client-side, to keep it out of the page's initial JS bundle — same pattern
// as /api/market/items.
export async function GET() {
  const access = await requireFullAccess();
  if (!access.ok) return access.response;

  return NextResponse.json(catalog);
}
