import { NextResponse } from "next/server";
import catalog from "@/data/item-catalog.json";

// Static catalog generated by scripts/build-item-catalog.mjs (npm run catalog:build).
// Bundled as JSON and served from here rather than imported client-side, to keep it
// out of the page's initial JS bundle.
export async function GET() {
  return NextResponse.json({ items: catalog });
}
